//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsService.SMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.ISMSService")]
    public interface ISMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSService/SendSMSGet", ReplyAction="http://tempuri.org/ISMSService/SendSMSGetResponse")]
        int SendSMSGet(string UserCode, string mobiles, string Content, string sendtime, string ValidTime, string AppendID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSService/SendSMSPost", ReplyAction="http://tempuri.org/ISMSService/SendSMSPostResponse")]
        int SendSMSPost(string UserCode, string mobiles, string Content, string sendtime, string ValidTime, string AppendID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSService/QueerySMSCount", ReplyAction="http://tempuri.org/ISMSService/QueerySMSCountResponse")]
        int QueerySMSCount();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSServiceChannel : SmsService.SMSService.ISMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceClient : System.ServiceModel.ClientBase<SmsService.SMSService.ISMSService>, SmsService.SMSService.ISMSService {
        
        public SMSServiceClient() {
        }
        
        public SMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SendSMSGet(string UserCode, string mobiles, string Content, string sendtime, string ValidTime, string AppendID) {
            return base.Channel.SendSMSGet(UserCode, mobiles, Content, sendtime, ValidTime, AppendID);
        }
        
        public int SendSMSPost(string UserCode, string mobiles, string Content, string sendtime, string ValidTime, string AppendID) {
            return base.Channel.SendSMSPost(UserCode, mobiles, Content, sendtime, ValidTime, AppendID);
        }
        
        public int QueerySMSCount() {
            return base.Channel.QueerySMSCount();
        }
    }
}
